name: flexible_calendar_widget
description: A customizable calendar widget for Flutter applications.
version: 1.0.0
homepage: https://github.com/oznurdemir/flutter_custom_calendar

environment:
  sdk: ">=3.4.1 <3.6.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

license: MIT
